### ISSUE TITLE
Don't crash if user tries to take stat holiday off

### ISSUE THREAD

**Issue by jollyra** [pulseenergy/vacation#3] opened 2015-11-27 18:34 UTC
I tried to "vacation dec 24,25" and it crashing. I think because 25 is a stat holiday.

**Comment by supermitch** [comment] 2015-12-03 02:52
Can't reproduce this. Taking stat holidays should make absolutely no difference (to that part of the code, anyway.)

What _is_ broken is `Dec 24,25` (without a space after the comma). Is that what broken during the demo? That's a lexer error.

**Comment by supermitch** [comment] 2015-12-05 04:47
Gonna close this issue since @jollyra won't test it for me.

**Closed as completed by supermitch** 2015-12-05 04:47 UTC
Labels: bug
